# Generated by Django 4.2 on 2024-03-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="Document",
            new_name="document",
        ),
    ]
